
services:
  passporting-service:
    build:
      context: .
      dockerfile: apps/passporting-server/Dockerfile
      args:
        TARGETPLATFORM: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - KWIL_NODE_URL=${KWIL_NODE_URL}
      - ISSUER_SIGNING_SECRET_KEY=${ISSUER_SIGNING_SECRET_KEY}
      - ISSUER_ENCRYPTION_SECRET_KEY=${ISSUER_ENCRYPTION_SECRET_KEY}
      - CLIENT_SECRETS=${CLIENT_SECRETS}
    env_file:
      - .env
    restart: unless-stopped 