packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"

catalogs:
  core:
    "@digitalbazaar/ed25519-signature-2020": "^5.4.0"
    "@digitalbazaar/ed25519-verification-key-2020": "^4.2.0"
    "@digitalbazaar/vc": "^7.2.0"
    "@gemwallet/api": "^3.8.0"
    "@kwilteam/kwil-js": "0.9.4"
    "@near-wallet-selector/core": "9.0.2"
    "@stablelib/base64": "^2.0.1"
    "@stablelib/binary": "^2.0.1"
    "@stablelib/bytes": "^2.0.1"
    "@stablelib/hex": "^2.0.1"
    "@stablelib/sha256": "^2.0.1"
    "@stablelib/utf8": "^2.0.1"
    "@stellar/stellar-sdk": "^13.3.0"
    "base85": "^3.1.0"
    "borsh": "^2.0.0"
    "bs58": "^6.0.0"
    "jsonld-document-loader": "^2.3.0"
    "es-toolkit": "^1.39.0"
    "ethers": "^6.14.0"
    "near-api-js": "^5.1.1"
    "tweetnacl": "^1.0.3"
    "tiny-invariant": "^1.3.3"
    "web-streams-polyfill": "^4.1.0"
    "ripple-binary-codec": "^2.4.0"
    "ripple-keypairs": "^2.0.0"
    "xrpl": "^4.3.0"
    "xumm": "^1.8.0"
    "zod": "^3.25.64"

  build:
    "tsdown": "^0.12.7"
    "typescript": "^5.8.3"

  testing:
    "vitest": "^3.2.2"

  react:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^19.1.0"
    "@types/react-dom": "^19.1.1"
