packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"

catalogs:
  core:
    "@digitalbazaar/ed25519-signature-2020": "^5.4.0"
    "@digitalbazaar/ed25519-verification-key-2020": "^4.2.0"
    "@digitalbazaar/vc": "^7.2.0"
    "@gemwallet/api": "^3.8.0"
    "@idos-network/kwil-js": "0.1.3"
    "jsonld-document-loader": "^2.3.0"
    "tweetnacl": "^1.0.3"
    "tiny-invariant": "^1.3.3"
    "web-streams-polyfill": "^4.1.0"
    "zod": "4.3.4"

  utils:
    "@stablelib/base64": "^2.0.1"
    "@stablelib/binary": "^2.0.1"
    "@stablelib/bytes": "^2.0.1"
    "@stablelib/hex": "^2.0.1"
    "@stablelib/sha256": "^2.0.1"
    "@stablelib/utf8": "^2.0.1"
    "base85": "^3.1.0"
    "borsh": "^2.0.0"
    "bs58": "^6.0.0"
    "es-toolkit": "^1.43.0"

  ethereum:
    "viem": "^2.14.0"
    "ethers": "^6.14.0"
    "wagmi": "^2.19.5"
    "@wagmi/core": "^2.22.1"

  reown:
    "@reown/appkit": "^1.7.13"
    "@reown/appkit-adapter-wagmi": "^1.7.13"

  near:
    "near-api-js": "4.0.3"
    "@near-wallet-selector/core": "8.10.2"
    "@near-wallet-selector/here-wallet": "8.10.2"
    "@near-wallet-selector/meteor-wallet": "8.10.2"
    "@near-wallet-selector/modal-ui": "8.10.2"

  stellar:
    "@stellar/stellar-sdk": "^13.3.0"
    "@stellar/stellar-base": "^13.1.0"
    "@creit.tech/stellar-wallets-kit": "^1.7.5"
    "@stellar/freighter-api": "^4.1.0"

  xrp:
    "xrpl": "^4.5.0"
    "xumm": "^1.8.0"
    "ripple-binary-codec": "^2.6.0"
    "ripple-keypairs": "^2.0.0"

  build:
    "vite": "^7.0.6"
    "typescript": "^5.9.3"
    "tsdown": "^0.18.0"
    "vite-plugin-node-polyfills": "0.17.0"

  testing:
    "vitest": "^4.0.6"

  react:
    "react": "^19.2.4"
    "react-dom": "^19.2.4"
    "@types/react": "^19.2.4"
    "@types/react-dom": "^19.2.3"

  preact:
    "preact": "^10.28.2"
    "@preact/signals": "^2.5.1"

  tanstack:
    "@tanstack/react-query": "^5.90.16"
    "@tanstack/react-query-devtools": "^5.91.2"
    "@tanstack/react-query-persist-client": "^5.90.18"
    "@tanstack/query-sync-storage-persister": "^5.90.18"
    "@tanstack/react-router": "^1.144.0"
    "@tanstack/react-router-devtools": "^1.144.0"
    "@tanstack/router-plugin": "^1.144.0"
