packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"

catalogs:
  core:
    "@digitalbazaar/ed25519-signature-2020": "^5.4.0"
    "@digitalbazaar/ed25519-verification-key-2020": "^4.2.0"
    "@digitalbazaar/vc": "^7.2.0"
    "@gemwallet/api": "^3.8.0"
    "@idos-network/kwil-js": "0.1.3"
    "jsonld-document-loader": "^2.3.0"
    "tweetnacl": "^1.0.3"
    "tiny-invariant": "^1.3.3"
    "web-streams-polyfill": "^4.1.0"
    "zod": "4.0.14"

  utils:
    "@stablelib/base64": "^2.0.1"
    "@stablelib/binary": "^2.0.1"
    "@stablelib/bytes": "^2.0.1"
    "@stablelib/hex": "^2.0.1"
    "@stablelib/sha256": "^2.0.1"
    "@stablelib/utf8": "^2.0.1"
    "base85": "^3.1.0"
    "borsh": "^2.0.0"
    "bs58": "^6.0.0"
    "es-toolkit": "^1.39.0"

  ethereum:
    "@wagmi/core": "^2.21.1"
    "wagmi": "^2.14.16"
    "viem": "^2.14.0"
    "ethers": "^6.14.0"

  reown:
    "@reown/appkit": "^1.7.13"
    "@reown/appkit-adapter-wagmi": "^1.7.13"

  near:
    "near-api-js": "4.0.3"
    "@near-wallet-selector/core": "8.10.2"
    "@near-wallet-selector/here-wallet": "8.10.2"
    "@near-wallet-selector/meteor-wallet": "8.10.2"
    "@near-wallet-selector/modal-ui": "8.10.2"

  stellar:
    "@stellar/stellar-sdk": "^14.0.2"
    "@stellar/stellar-base": "^14.0.1"
    "@creit.tech/stellar-wallets-kit": "^1.9.5"
    "@stellar/freighter-api": "^5.0.0"

  xrp:
    "xrpl": "^4.3.0"
    "xumm": "^1.8.0"
    "ripple-binary-codec": "^2.4.0"
    "ripple-keypairs": "^2.0.0"

  build:
    "vite": "^7.0.6"
    "typescript": "^5.8.3"
    "tsdown": "^0.15.6"
    "vite-plugin-node-polyfills": "0.17.0"

  testing:
    "vitest": "^3.2.2"

  react:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^19.1.0"
    "@types/react-dom": "^19.1.1"

  tanstack:
    "@tanstack/react-query": "^5.72.1"
    "@tanstack/react-query-devtools": "^5.72.1"
    "@tanstack/react-query-persist-client": "^5.72.1"
    "@tanstack/query-sync-storage-persister": "^5.72.1"
    "@tanstack/react-router": "^1.115.2"
    "@tanstack/react-router-devtools": "^1.115.2"
    "@tanstack/router-plugin": "^1.115.2"
