packages:
  - apps/*
  - examples/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@digitalbazaar/ed25519-signature-2020": ^5.2.0
  "@digitalbazaar/ed25519-verification-key-2020": ^4.1.0
  "@digitalbazaar/vc": ^6.0.2
  "@dotenvx/dotenvx": ^1.6.4
  "@emotion/react": ^11.13.0
  "@emotion/styled": ^11.13.0
  "@headlessui/react": 2.1.8
  "@heroicons/react": ^2.1.3
  "@heroui/react": 2.6.14
  "@hono/node-server": ^1.13.7
  "@hono/zod-validator": ^0.4.2
  "@kwilteam/kwil-js": 0.7.1
  "@lit-protocol/auth-helpers": ^6.4.10
  "@lit-protocol/constants": ^6.5.0
  "@lit-protocol/lit-node-client": ^6.4.10
  "@lit-protocol/types": ^6.5.0
  "@near-js/types": ^0.2.1
  "@near-wallet-selector/core": 8.9.10
  "@near-wallet-selector/modal-ui": 8.9.10
  "@near-wallet-selector/modal-ui-js": ^8.7.0
  "@near-wallet-selector/my-near-wallet": ^8.7.0
  "@near-wallet-selector/nightly": ^8.7.0
  "@preact/signals": ^1.3.0
  "@react-oauth/google": ^0.12.1
  "@release-it/keep-a-changelog": ^5.0.0
  "@stablelib/base64": ^1.0.1
  "@stablelib/binary": ^1.0.1
  "@stablelib/bytes": ^1.0.1
  "@stablelib/hex": ^2.0.0
  "@stablelib/sha256": ^1.0.1
  "@stablelib/utf8": ^1.0.1
  "@synthetixio/synpress": ^4.0.3
  "@synthetixio/synpress-cache": ^0.0.4
  "@synthetixio/synpress-metamask": ^0.0.4
  "@tailwindcss/forms": ^0.5.6
  "@tailwindcss/vite": ^4.0.1
  "@tanstack/query-sync-storage-persister": ^5.59.20
  "@tanstack/react-query-persist-client": ^5.59.20
  "@tanstack/react-router": ^1.77.8
  "@tanstack/router-devtools": ^1.77.8
  "@tanstack/router-plugin": ^1.77.7
  "@testing-library/react": ^14.3.1
  "@types/dompurify": 3.0.5
  "@types/lodash-es": ^4.17.12
  "@uidotdev/usehooks": ^2.4.1
  "@vercel/node": ^3.0.26
  "@vitest/ui": ^0.34.6
  "@web3modal/wagmi": ^4.2.3
  ascii85: ^1.0.2
  axios: ^1.6.8
  borsh: ^1.0.0
  bs58: ^6.0.0
  bufferutil: ^4.0.8
  clean-package: ^2.2.0
  dompurify: ^3.0.6
  dotenv: ^16.4.5
  encoding: ^0.1.13
  es-toolkit: ^1.23.0
  globals: ^15.11.0
  go-try: ^3.0.2
  hono: ^4.6.16
  jsdom: ^22.1.0
  jsonld: ^8.3.1
  jsonld-document-loader: ^2.0.0
  lefthook: 1.7.5
  lodash-es: ^4.17.21
  lokijs: ^1.5.12
  match-sorter: ^7.0.0
  near-api-js: 3.0.4
  next-themes: ^0.4.4
  pino-pretty: ^10.3.1
  playwright-core: ^1.49.1
  playwright-test-coverage: ^1.2.12
  prettier: ^3.0.3
  raw-body: ^2.5.2
  react-aria-components: ^1.6.0
  react-icons: ^5.4.0
  react-router-dom: ^6.25.1
  release-it: ^17.0.0
  scrypt-js: ^3.0.1
  supports-color: ^8.1.1
  tailwind-variants: ^0.2.1
  tailwindcss-animate: ^1.0.7
  tiny-invariant: ^1.3.3
  tsup: 8.0.2
  tsx: ^4.7.1
  turbo: ^2.3.3
  tweetnacl: ^1.0.3
  utf-8-validate: ^5.0.2
  vite-plugin-html: ^3.2.0
  vite-plugin-node-polyfills: ^0.12.0
  vite-tsconfig-paths: ^5.1.4
  web-bip39: ^0.0.3
  zod: ^3.24.1
  zustand: ^5.0.0
