import invariant from "tiny-invariant";

const VITE_FACESIGN_SERVICE_URL = import.meta.env.VITE_FACESIGN_SERVICE_URL;
const VITE_ENTROPY_SERVICE_URL = import.meta.env.VITE_ENTROPY_SERVICE_URL;
const VITE_FACETEC_DEVICE_KEY_IDENTIFIER = import.meta.env.VITE_FACETEC_DEVICE_KEY_IDENTIFIER;
const VITE_FACETEC_BRANDING_IMAGE = import.meta.env.VITE_FACETEC_BRANDING_IMAGE;
const VITE_ALLOWED_ORIGINS = import.meta.env.VITE_ALLOWED_ORIGINS;

invariant(VITE_FACESIGN_SERVICE_URL, "VITE_FACESIGN_SERVICE_URL must be set");
invariant(VITE_ENTROPY_SERVICE_URL, "VITE_ENTROPY_SERVICE_URL must be set");
invariant(VITE_FACETEC_DEVICE_KEY_IDENTIFIER, "VITE_FACETEC_DEVICE_KEY_IDENTIFIER must be set");

export const env = {
  VITE_FACESIGN_SERVICE_URL: VITE_FACESIGN_SERVICE_URL,
  VITE_ENTROPY_SERVICE_URL: VITE_ENTROPY_SERVICE_URL,
  VITE_FACETEC_DEVICE_KEY_IDENTIFIER: VITE_FACETEC_DEVICE_KEY_IDENTIFIER,
  /** Overlay logo shown during FaceTec flow. Defaults to /logo.svg if unset. */
  VITE_FACETEC_BRANDING_IMAGE: VITE_FACETEC_BRANDING_IMAGE,
  VITE_ALLOWED_ORIGINS: VITE_ALLOWED_ORIGINS,
};
