import invariant from "tiny-invariant";

const VITE_FACESIGN_SERVICE_URL = import.meta.env.VITE_FACESIGN_SERVICE_URL;
const VITE_ENTROPY_SERVICE_URL = import.meta.env.VITE_ENTROPY_SERVICE_URL;
const VITE_FACETEC_DEVICE_KEY_IDENTIFIER = import.meta.env.VITE_FACETEC_DEVICE_KEY_IDENTIFIER;
const VITE_FACETEC_IFRAME_FEATURE_FLAG = import.meta.env.VITE_FACETEC_IFRAME_FEATURE_FLAG;
const VITE_ALLOWED_ORIGINS = import.meta.env.VITE_ALLOWED_ORIGINS;

invariant(VITE_FACESIGN_SERVICE_URL, "VITE_FACESIGN_SERVICE_URL must be set");
invariant(VITE_ENTROPY_SERVICE_URL, "VITE_ENTROPY_SERVICE_URL must be set");
invariant(VITE_FACETEC_DEVICE_KEY_IDENTIFIER, "VITE_FACETEC_DEVICE_KEY_IDENTIFIER must be set");
invariant(VITE_FACETEC_IFRAME_FEATURE_FLAG, "VITE_FACETEC_IFRAME_FEATURE_FLAG must be set");

export const env = {
  VITE_FACESIGN_SERVICE_URL: VITE_FACESIGN_SERVICE_URL,
  VITE_ENTROPY_SERVICE_URL: VITE_ENTROPY_SERVICE_URL,
  VITE_FACETEC_DEVICE_KEY_IDENTIFIER: VITE_FACETEC_DEVICE_KEY_IDENTIFIER,
  VITE_FACETEC_IFRAME_FEATURE_FLAG: VITE_FACETEC_IFRAME_FEATURE_FLAG,
  VITE_ALLOWED_ORIGINS: VITE_ALLOWED_ORIGINS,
};
