export const env = {
  VITE_FACESIGN_SERVICE_URL: import.meta.env.VITE_FACESIGN_SERVICE_URL,
  VITE_ENTROPY_SERVICE_URL: import.meta.env.VITE_ENTROPY_SERVICE_URL,
  VITE_FACETEC_DEVICE_KEY_IDENTIFIER: import.meta.env.VITE_FACETEC_DEVICE_KEY_IDENTIFIER,
  VITE_ALLOWED_ORIGINS: import.meta.env.VITE_ALLOWED_ORIGINS,
};
