/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedWalletRouteImport } from './routes/_protected/wallet'
import { Route as ProtectedSignRouteImport } from './routes/_protected/sign'
import { Route as ProtectedSessionRouteImport } from './routes/_protected/session'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWalletRoute = ProtectedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSignRoute = ProtectedSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSessionRoute = ProtectedSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/session': typeof ProtectedSessionRoute
  '/sign': typeof ProtectedSignRoute
  '/wallet': typeof ProtectedWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/session': typeof ProtectedSessionRoute
  '/sign': typeof ProtectedSignRoute
  '/wallet': typeof ProtectedWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_protected/session': typeof ProtectedSessionRoute
  '/_protected/sign': typeof ProtectedSignRoute
  '/_protected/wallet': typeof ProtectedWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/error' | '/login' | '/session' | '/sign' | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error' | '/login' | '/session' | '/sign' | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/error'
    | '/login'
    | '/_protected/session'
    | '/_protected/sign'
    | '/_protected/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/wallet': {
      id: '/_protected/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof ProtectedWalletRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sign': {
      id: '/_protected/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof ProtectedSignRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/session': {
      id: '/_protected/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof ProtectedSessionRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSessionRoute: typeof ProtectedSessionRoute
  ProtectedSignRoute: typeof ProtectedSignRoute
  ProtectedWalletRoute: typeof ProtectedWalletRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSessionRoute: ProtectedSessionRoute,
  ProtectedSignRoute: ProtectedSignRoute,
  ProtectedWalletRoute: ProtectedWalletRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
