import type {
  Ed25519VerificationKey2020,
  Ed25519VerificationKey2020Options,
} from "@digitalbazaar/ed25519-verification-key-2020";

export interface CustomIssuerType {
  issuer: string;

  /* Multibase encoded public key */
  publicKeyMultibase: string;

  /* Multibase encoded private key */
  privateKeyMultibase?: string;

  /* id and controller will be generated by the library */
}

export type AvailableIssuerType =
  | Omit<Ed25519VerificationKey2020Options, "type">
  | Ed25519VerificationKey2020
  | CustomIssuerType;
