// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/file": {
    params: {};
  };
  "/callbacks/noah": {
    params: {};
  };
  "/callbacks/hifi/tos": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/kyc/token": {
    params: {};
  };
  "/app/kyc/data": {
    params: {};
  };
  "/app/kyc/link": {
    params: {};
  };
  "/app/kyc/noah/link": {
    params: {};
  };
  "/app/kyc/hifi/tos": {
    params: {};
  };
  "/app/kyc/hifi/link": {
    params: {};
  };
  "/app/kyc/hifi/account": {
    params: {};
  };
  "/app/kyc/hifi/status": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/file" | "/callbacks/noah" | "/callbacks/hifi/tos" | "/app" | "/app/kyc/token" | "/app/kyc/data" | "/app/kyc/link" | "/app/kyc/noah/link" | "/app/kyc/hifi/tos" | "/app/kyc/hifi/link" | "/app/kyc/hifi/account" | "/app/kyc/hifi/status";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/file.ts": {
    id: "routes/file";
    page: "/file";
  };
  "routes/callbacks/noah.tsx": {
    id: "routes/callbacks/noah";
    page: "/callbacks/noah";
  };
  "routes/callbacks/hifi/tos.tsx": {
    id: "routes/callbacks/hifi/tos";
    page: "/callbacks/hifi/tos";
  };
  "layouts/app.tsx": {
    id: "layouts/app";
    page: "/app" | "/app/kyc/token" | "/app/kyc/data" | "/app/kyc/link" | "/app/kyc/noah/link" | "/app/kyc/hifi/tos" | "/app/kyc/hifi/link" | "/app/kyc/hifi/account" | "/app/kyc/hifi/status";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/kyc/token.ts": {
    id: "routes/kyc/token";
    page: "/app/kyc/token";
  };
  "routes/kyc/data.ts": {
    id: "routes/kyc/data";
    page: "/app/kyc/data";
  };
  "routes/kyc/link.ts": {
    id: "routes/kyc/link";
    page: "/app/kyc/link";
  };
  "routes/kyc/noah/link.ts": {
    id: "routes/kyc/noah/link";
    page: "/app/kyc/noah/link";
  };
  "routes/kyc/hifi/tos.ts": {
    id: "routes/kyc/hifi/tos";
    page: "/app/kyc/hifi/tos";
  };
  "routes/kyc/hifi/link.ts": {
    id: "routes/kyc/hifi/link";
    page: "/app/kyc/hifi/link";
  };
  "routes/kyc/hifi/account.ts": {
    id: "routes/kyc/hifi/account";
    page: "/app/kyc/hifi/account";
  };
  "routes/kyc/hifi/status.ts": {
    id: "routes/kyc/hifi/status";
    page: "/app/kyc/hifi/status";
  };
};