#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(dirname, "..");
const require = createRequire(import.meta.url);
const tscPath = require.resolve("typescript/bin/tsc");

// Utility functions
function capitalize(value) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function formatFile(filePath) {
  const result = spawnSync(
    process.platform === "win32" ? "pnpm.cmd" : "pnpm",
    ["exec", "oxfmt", filePath],
    { cwd: packageRoot, stdio: "inherit" },
  );

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`Failed to format ${path.relative(packageRoot, filePath)}`);
  }
}

function formatFile(filePath) {
  const result = spawnSync(
    process.platform === "win32" ? "pnpm.cmd" : "pnpm",
    ["exec", "oxfmt", filePath],
    { cwd: packageRoot, stdio: "inherit" },
  );

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`Failed to format ${path.relative(packageRoot, filePath)}`);
  }
}

// Configuration & directory paths
const configuration = [
  {
    dir: "credentialSubjectV3",
    jsonLd: "idos-credential-subject-v3.json",
    ts: "credentialSubjectV3.generated.ts",
    prefix: "CredentialSubject",
  },
  {
    dir: "faceIdV1",
    jsonLd: "idos-credential-subject-face-id-v1.json",
    ts: "faceIdV1.generated.ts",
    prefix: "FaceId",
  },
];

const entitiesRoot = path.join(packageRoot, "src/schemas/");
const jsonLdRoot = path.join(packageRoot, "assets/");
const tsRoot = path.join(packageRoot, "src/types/");

function compileEntities(entitiesRoot) {
  const tmpParent = path.join(packageRoot, ".tmp");
  fs.mkdirSync(tmpParent, { recursive: true });
  const tmpRoot = fs.mkdtempSync(path.join(tmpParent, "json-ld-"));
  fs.writeFileSync(path.join(tmpRoot, "package.json"), JSON.stringify({ type: "commonjs" }));

  const result = spawnSync(
    process.execPath,
    [
      tscPath,
      entitiesIndexPath,
      "--outDir",
      tmpRoot,
      "--rootDir",
      entitiesRoot,
      "--target",
      "ES2022",
      "--module",
      "CommonJS",
      "--moduleResolution",
      "node10",
      "--skipLibCheck",
      "--esModuleInterop",
      "--noCheck",
    ],
    { cwd: packageRoot, stdio: "inherit" },
  );

  if (result.status !== 0) {
    fs.rmSync(tmpRoot, { recursive: true, force: true });
    throw new Error("Failed to compile credential subject entities");
  }

  return tmpRoot;
}

function renderJsonLd(credentialSubjectMapping) {
  const context = {
    "@version": 1.1,
    "@protected": true,
    xsd: "http://www.w3.org/2001/XMLSchema#",
  };

  for (const [prefix, schema] of Object.entries(credentialSubjectMapping)) {
    for (const [fieldName, fieldSchema] of Object.entries(schema.shape)) {
      context[`${prefix}${capitalize(fieldName)}`] = getContextType(fieldSchema);
    }
  }

  return `${JSON.stringify({ "@context": context }, null, 2)}\n`;
}

function findSchemaExport(schema, tmpRoot) {
  for (const fileName of fs.readdirSync(tmpRoot)) {
    if (!fileName.endsWith(".js") || fileName === "index.js") {
      continue;
    }

    const exports = require(path.join(tmpRoot, fileName));
    for (const [exportName, exportedValue] of Object.entries(exports)) {
      if (exportedValue === schema) {
        return {
          exportName,
          importPath: `${generatedTypesImportRoot}/${fileName.replace(/\.js$/, "")}`,
        };
      }
    }
  }

  throw new Error("Unable to find source export for credential subject schema");
}

function getSchemaMetadata(credentialSubjectMapping, tmpRoot) {
  return Object.entries(credentialSubjectMapping).map(([prefix, schema]) => ({
    prefix,
    schema,
    ...findSchemaExport(schema, tmpRoot),
  }));
}

function renderSubjectTypes(credentialSubjectMapping, tmpRoot) {
  const schemas = getSchemaMetadata(credentialSubjectMapping, tmpRoot);

  const imports = schemas
    .map(({ exportName, importPath }) => `import { ${exportName} } from "${importPath}";`)
    .join("\n");

  const fields = [];
  const typeDefinitions = [];

  for (const { prefix, schema, exportName } of schemas) {
    for (const [fieldName, fieldSchema] of Object.entries(schema.shape)) {
      const verifiableFieldName = `${prefix}${capitalize(fieldName)}`;
      const sourceExpression = `${exportName}.shape.${fieldName}`;
      fields.push(`  ${verifiableFieldName}: ${sourceExpression},`);
      typeDefinitions.push(`  ${verifiableFieldName}: typeof ${sourceExpression},`);
    }
  }

  return `/* This file is generated by packages/credentials/cli/generate-subject.mjs. */
import { z } from "zod";

${imports}

export const VerifiableCredentialV3Schema: z.ZodObject<{
${typeDefinitions.join("\n")}
}> = z.object({
${fields.join("\n")}
});

export type VerifiableCredentialV3 = z.infer<typeof VerifiableCredentialV3Schema>;
`;
}

function main() {
  for (const { dir, jsonLd, ts, prefix } of configuration) {
    const entitiesRoot = path.join(packageRoot, "src/schemas/", dir);
    const jsonLdPath = path.join(packageRoot, "assets/", jsonLd);
    const subjectTypesPath = path.join(packageRoot, "src/types/", ts);
    const generatedTypesImportRoot = `../schemas/${dir}`;

    const tmpRoot = compileEntities(entitiesRoot);

    try {
      const { default: mapping } = require(path.join(tmpRoot, "index.js"));

      fs.rmSync(jsonLdPath, { force: true });
      fs.rmSync(subjectTypesPath, { force: true });

      fs.writeFileSync(jsonLdPath, renderJsonLd(mapping));
      formatFile(jsonLdPath);
      fs.writeFileSync(subjectTypesPath, renderSubjectTypes(mapping, tmpRoot));
      formatFile(subjectTypesPath);
    } finally {
      fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
  }
}

main();
