import * as z from "zod";

export const OccupationSchema: z.ZodEnum<{
  AGRICULTURE: "AGRICULTURE";
  ARTS_AND_ENTERTAINMENT: "ARTS_AND_ENTERTAINMENT";
  CONSTRUCTION: "CONSTRUCTION";
  EDUCATION: "EDUCATION";
  FINANCIAL_SERVICES: "FINANCIAL_SERVICES";
  INFORMATION_AND_TECHNOLOGY: "INFORMATION_AND_TECHNOLOGY";
  RETAIL: "RETAIL";
  REAL_ESTATE: "REAL_ESTATE";
  OTHER: "OTHER";
  BUSINESS_OWNER: "BUSINESS_OWNER";
  HEALTHCARE: "HEALTHCARE";
  INDUSTRIAL: "INDUSTRIAL";
  LEGAL_SERVICES: "LEGAL_SERVICES";
  PUBLIC_SECTOR: "PUBLIC_SECTOR";
  SENIOR_MANAGEMENT: "SENIOR_MANAGEMENT";
}> = z.enum([
  "AGRICULTURE",
  "ARTS_AND_ENTERTAINMENT",
  "CONSTRUCTION",
  "EDUCATION",
  "FINANCIAL_SERVICES",
  "INFORMATION_AND_TECHNOLOGY",
  "RETAIL",
  "REAL_ESTATE",
  "OTHER",
  "BUSINESS_OWNER",
  "HEALTHCARE",
  "INDUSTRIAL",
  "LEGAL_SERVICES",
  "PUBLIC_SECTOR",
  "SENIOR_MANAGEMENT",
]);
export type Occupation = z.infer<typeof OccupationSchema>;
