name: Playwright Tests (Playground @ develop)
on:
  push:
    branches: [ develop ]

jobs:
  e2e:
    environment: Playground
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./apps/idos-sdk-e2e
    env:
      BASE_URL: ${{secrets.IDOS_E2E_BASE_URL}}
      WALLET_SEED_PHRASE: ${{ secrets.IDOS_E2E_WALLET_SEED_PHRASE }}
      WALLET_PASSWORD: ${{ secrets.IDOS_E2E_WALLET_PASSWORD }}
      GRANTS_TEST_BASE_URL: ${{ secrets.IDOS_E2E_GRANTS_BASE_URL }}
      CREDENTIAL_CONTENT: ${{ secrets.IDOS_E2E_CREDENTIAL_CONTENT }}
      CREDENTIAL_ID: ${{ secrets.IDOS_E2E_CREDENTIAL_ID }}
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version-file: .node_version
        cache: 'pnpm'

    - run: pnpm install

    - name: Install Playwright
      run: pnpm playwright install --with-deps chromium

    - name: Build Synpress cache
      run: xvfb-run npx synpress ./wallet-setup

    - name: Run Playwright tests
      run: xvfb-run npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
