name: Typecheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - playground
      - main

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - uses: pnpm/action-setup@v5
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install packages
        run: pnpm install

      - name: Run audit
        run: pnpm exec audit-ci --package-manager pnpm --high --critical
